# Cloudflare Workers Configuration for WT POS & Payroll SaaS
# This configuration uses the free tier of Cloudflare Workers and D1 Database

name = "wt-pos-payroll-saas"
main = "src/worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
COMPANY_NAME = "Your Company Name"
JWT_EXPIRES_IN = "7d"

[[kv_namespaces]]
binding = "CACHE"
id = "53480cdb256b4095ac269c95c8320104"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "wt-pos-payroll-storage"

[build]
command = "npm run build"

# Environment-specific configurations
[env.development]
name = "wt-pos-payroll-saas-dev"
vars = { ENVIRONMENT = "development" }

[env.staging]
name = "wt-pos-payroll-saas-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "wt-pos-payroll-saas"
vars = { ENVIRONMENT = "production" }

# Cron triggers for automated tasks
[triggers]
crons = [
  "0 0 * * *",  # Daily at midnight - backup and maintenance
  "0 6 * * 1",  # Weekly on Monday at 6 AM - payroll processing
  "0 2 * * *"   # Daily at 2 AM - analytics aggregation
] 